Feautre/#41
sulton-max/Training.TestGorilla.Clone pull request #50
Opened 2023-09-27 15:04 UTC by FirdavsAsadov

merge qiliylar

2023-09-27 15:05 UTC, Ozodbek4 submitted a review, later dismissed

2023-09-27 15:05 UTC, Jasurbek1223 submitted a review, later dismissed

2023-09-28 11:20 UTC, Jasurbek1223 submitted a review, later dismissed

2023-09-28 11:31 UTC, Amonov996 requested changes

2023-09-28 11:31 UTC, Amonov996 commented on src/Training.TestGorilla.Clone.Backend/TestGorilla.Service/Helpers/Validator.cs
> +    public bool IsValidName(string name) =>
Add  here free line

2023-09-28 11:31 UTC, Amonov996 commented on src/Training.TestGorilla.Clone.Backend/TestGorilla.Service/Services/MultipleChoiceQuestionService.cs
> +{
make a clean namespace

2023-09-28 11:31 UTC, Amonov996 commented on src/Training.TestGorilla.Clone.Backend/TestGorilla.Service/Services/Interfaces/IMultipleChoiceQuestionService.cs
> +{
make a clean namespace

2023-09-28 11:46 UTC, Amonov996 approved these changes, later dismissed

2023-09-28 11:51 UTC, Amonov996 approved these changes

2023-09-28 11:51 UTC, Amonov996 approved these changes

2023-09-28 11:51 UTC, Jasurbek1223 approved these changes

2023-09-28 11:52 UTC, merged